'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Proposal_WhereNow

    '''<summary>
    '''btnGetNow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGetNow As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblNow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNow As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnGetAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGetAll As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAll As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''accordion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents accordion As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''uctrlDayOne control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uctrlDayOne As Global.WebApplication1.ctrl_rptCheatCode

    '''<summary>
    '''uctrlDayTwo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uctrlDayTwo As Global.WebApplication1.ctrl_rptCheatCode

    '''<summary>
    '''uctrlDayThree control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uctrlDayThree As Global.WebApplication1.ctrl_rptCheatCode

    '''<summary>
    '''uctrlDayFour control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uctrlDayFour As Global.WebApplication1.ctrl_rptCheatCode

    '''<summary>
    '''uctrlDayFive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uctrlDayFive As Global.WebApplication1.ctrl_rptCheatCode

    '''<summary>
    '''uctrlDaySix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uctrlDaySix As Global.WebApplication1.ctrl_rptCheatCode

    '''<summary>
    '''uctrlDaySeven control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uctrlDaySeven As Global.WebApplication1.ctrl_rptCheatCode

    '''<summary>
    '''uctrlDayEight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uctrlDayEight As Global.WebApplication1.ctrl_rptCheatCode

    '''<summary>
    '''uctrlDayNine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uctrlDayNine As Global.WebApplication1.ctrl_rptCheatCode

    '''<summary>
    '''uctrlDayTen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uctrlDayTen As Global.WebApplication1.ctrl_rptCheatCode
End Class
