'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Proposal_PicVideos

    '''<summary>
    '''uctrlPhotoOmaha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uctrlPhotoOmaha As Global.WebApplication1.ctrl_rptPhoto

    '''<summary>
    '''uctrlPhotoBoston control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uctrlPhotoBoston As Global.WebApplication1.ctrl_rptPhoto

    '''<summary>
    '''uctrlPhotoProposal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uctrlPhotoProposal As Global.WebApplication1.ctrl_rptPhoto

    '''<summary>
    '''uctrlPhotoTulum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uctrlPhotoTulum As Global.WebApplication1.ctrl_rptPhoto

    '''<summary>
    '''uctrlPhotoChichenItza control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uctrlPhotoChichenItza As Global.WebApplication1.ctrl_rptPhoto

    '''<summary>
    '''uctrlPhotoHardRock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uctrlPhotoHardRock As Global.WebApplication1.ctrl_rptPhoto

    '''<summary>
    '''uctrlPhotoRandoms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uctrlPhotoRandoms As Global.WebApplication1.ctrl_rptPhoto

    '''<summary>
    '''uctrlVideos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uctrlVideos As Global.WebApplication1.ctrl_rptPhoto
End Class
