'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Proposal_WhereNow

    '''<summary>
    '''btnGetNow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGetNow As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblNow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNow As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnGetAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGetAll As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAll As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''uctrlTest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uctrlTest As Global.WebApplication1.ctrl_rptCheatCode

    '''<summary>
    '''rptDayOne control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptDayOne As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''rptDayTwo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptDayTwo As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''rptDayThree control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptDayThree As Global.System.Web.UI.WebControls.Repeater
End Class
